
import asyncio
from sqlalchemy import text
from app.db.session import AsyncSessionLocal

async def test_issue():
    print("--- Starting Reproduction Test ---")
    async with AsyncSessionLocal() as session:
        try:
            # This represents a query generated by the LLM: 
            # "SELECT * FROM task_transaction WHERE scheduled_date LIKE '2025-01-22%'"
            # In SQLAlchemy text(), the '%' is interpreted as a bind parameter placeholder.
            query = "SELECT 1 as id WHERE '2025-01-22' LIKE '2025-01-22%'"
            
            print(f"Executing: {query}")
            # This is expected to FAIL with a "TypeError: ... has too few arguments" or similar
            await session.execute(text(query))
            print("SUCCESS (Unexpected): Query ran without error.")
            
        except Exception as e:
            print(f"FAILURE (Expected): {type(e).__name__}: {e}")
            print("Explanation: SQLAlchemy tried to find a bind parameter for '%' and failed.")

async def test_fix():
    print("\n--- Starting Fix Verification ---")
    async with AsyncSessionLocal() as session:
        try:
            # The Fix: Replace '%' with '%%'
            query = "SELECT 1 as id WHERE '2025-01-22' LIKE '2025-01-22%'"
            safe_query = query.replace("%", "%%")
            
            print(f"Executing Safe Query: {safe_query}")
            await session.execute(text(safe_query))
            print("SUCCESS: Query ran successfully with escaping!")
            
        except Exception as e:
            print(f"FAILURE: {type(e).__name__}: {e}")

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test_issue())
    loop.run_until_complete(test_fix())
